### ISSUE TITLE
Better deployment strategy for Beanstalk

### ISSUE THREAD

**Issue by romanchyla** [adsabs/adsabs-aws#8]
So I'd like to describe the current pains and wishes with the Elastic Beanstalk, I don't know if they can all be solved, but we should at least think how to alleviate them:

1. it takes long time to deploy (and by long I mean the current 5-10 mins - it is an awful wait to be told that something failed ;))
2. when it fails, the AWS says it is running new version (ie. v.1.0.9:release) but in fact it is running the previous version (because deployment of that particular version failed - this the case of hourly bbb right now)
3. One always has to upload a new deployment.zip, and the only thing that is changing there is the tag version; I cant imagine that in time of emergency, it will be very pleasant to fiddle through zip,upload,deploy... (well: somewhat related to this point is the following: that deployment.zip contains some config and some commands, if I'm not careful, I can use a config from some previous releases - with a different config. eg. wrong shim.html - and we'll not know until a user hits the bug; we are basically increasing the likelihood that something goes wrong)

I can live with points 1 and 2, if they have to stay, but we should really do something with the last

in the past I already tried - configuring it to get the latest git release ```git checkout `git describe --abbrev=0 --tags```` but for some mysterious reason it failed

but ideally, i would just need to click deploy, specify correct release name (ie. tag) and hit deploy; without having to upload anything

can the release tag be passed on as an environment variable?

**Comment by vsudilov** [comment]
Closing for now; we are a far way away (technically) from continuous deployments
